language: c
sudo: required
dist: trusty
env:
  matrix:
    - CFG="--disable-websocket --disable-webinterface --disable-verification"
    - CFG="--disable-websocket --disable-webinterface --enable-lastfm --disable-verification"
    - CFG="--disable-websocket --disable-webinterface --enable-spotify --disable-verification"
    - CFG="--disable-websocket --disable-webinterface --enable-chromecast --disable-verification"
    - CFG="--disable-websocket --disable-webinterface --with-pulseaudio --disable-verification"

script:
  - autoreconf -fi
  - ./configure $CFG
  - make
  - make clean
  - scan-build --status-bugs -disable-checker deadcode.DeadStores make

before_install:
  - wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
  - sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/jessie.list
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential clang git autotools-dev autoconf libtool gettext gawk gperf antlr3 libantlr3c-dev libconfuse-dev libunistring-dev libsqlite3-dev libavcodec-dev libavformat-dev libavfilter-dev libswscale-dev libavutil-dev libasound2-dev libmxml-dev libgcrypt11-dev libavahi-client-dev zlib1g-dev libevent-dev libplist-dev libcurl4-openssl-dev libjson-c-dev libspotify-dev libgnutls-dev libprotobuf-c0-dev libpulse-dev
  
# Disable email notification
notifications:
  email: false
